version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql_unab
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=unab
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_DB_DRIVER: mysql
    ports:
      - 8080:8080
volumes:
  postgres_data: